import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
/**
 * APP LAYOUT
 * Route: /app/*
 *
 * TODO: Implement the following features:
 * - [ ] Authentication check (redirect to /login if not authenticated)
 * - [ ] Render main Header component
 * - [ ] Render Sidebar component with navigation
 * - [ ] Main content area with children
 * - [ ] Socket.IO connection (useSocket hook)
 * - [ ] Load user data on mount (useAuth hook)
 * - [ ] Two-column layout (sidebar + content)
 * - [ ] Mobile responsive (hamburger menu on mobile)
 * - [ ] Handle socket connection errors
 * - [ ] Show loading state while auth is loading
 * - [ ] Background color/styling from globals.css
 * - [ ] Tailwind responsive classes
 */
